### ISSUE TITLE
Redirect from www.v2ex.pro and v2ex.pro to cl.v2ex.pro

### ISSUE THREAD

**Issue by livid** [v2ex/launcher-website#10]
What would be the ideal method to implement such a trivial and common redirection?

**Comment by xieyuheng** [comment]
I use vercel.com to host my domain and website, vercel can do redirections by config such as:

![2022-01-11-205313_3000x2000_scrot](https://user-images.githubusercontent.com/4354888/148946222-2a87bf76-c6b4-4b87-8f1c-5a2190088b66.png)

**Comment by livid** [comment]
@xieyuheng Thank you! I have got this working on Vercel. Very nice!
